package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name = "BankAccount", catalog = "weasleydb")
@XmlRootElement
public class BankAccount implements java.io.Serializable {

	private Long bankAccountId;
	private String bankName;
	private String routingNumber;
	private String accountNumber;
	private Date accountOpenDate;
	private Date accountCloseDate;
	private Long corporateAddress;
	private Long branchAddress;
	private String phoneNumber;
	private Long customerId;

	public BankAccount() {
	}

	public BankAccount(String bankName, String routingNumber,
			String accountNumber) {
		this.bankName = bankName;
		this.routingNumber = routingNumber;
		this.accountNumber = accountNumber;
	}
	public BankAccount(String bankName, String routingNumber,
			String accountNumber, Date accountOpenDate, Date accountCloseDate,
			Long corporateAddress, Long branchAddress, String phoneNumber,
			Long customerId) {
		this.bankName = bankName;
		this.routingNumber = routingNumber;
		this.accountNumber = accountNumber;
		this.accountOpenDate = accountOpenDate;
		this.accountCloseDate = accountCloseDate;
		this.corporateAddress = corporateAddress;
		this.branchAddress = branchAddress;
		this.phoneNumber = phoneNumber;
		this.customerId = customerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bankAccountId", unique = true, nullable = false)
	public Long getBankAccountId() {
		return this.bankAccountId;
	}

	public void setBankAccountId(Long bankAccountId) {
		this.bankAccountId = bankAccountId;
	}

	@Column(name = "bankName", nullable = false, length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "routingNumber", nullable = false, length = 20)
	public String getRoutingNumber() {
		return this.routingNumber;
	}

	public void setRoutingNumber(String routingNumber) {
		this.routingNumber = routingNumber;
	}

	@Column(name = "accountNumber", nullable = false, length = 20)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "accountOpenDate", length = 10)
	public Date getAccountOpenDate() {
		return this.accountOpenDate;
	}

	public void setAccountOpenDate(Date accountOpenDate) {
		this.accountOpenDate = accountOpenDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "accountCloseDate", length = 10)
	public Date getAccountCloseDate() {
		return this.accountCloseDate;
	}

	public void setAccountCloseDate(Date accountCloseDate) {
		this.accountCloseDate = accountCloseDate;
	}

	@Column(name = "corporateAddress")
	public Long getCorporateAddress() {
		return this.corporateAddress;
	}

	public void setCorporateAddress(Long corporateAddress) {
		this.corporateAddress = corporateAddress;
	}

	@Column(name = "branchAddress")
	public Long getBranchAddress() {
		return this.branchAddress;
	}

	public void setBranchAddress(Long branchAddress) {
		this.branchAddress = branchAddress;
	}

	@Column(name = "phoneNumber", length = 25)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "customerId")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

}
