package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CustomerNote generated by hbm2java
 */
@Entity
@Table(name = "CustomerNote", catalog = "weasleydb")
@XmlRootElement
public class CustomerNote implements java.io.Serializable {

	private Long customerNoteId;
	private Long customerId;
	private Long noteId;

	public CustomerNote() {
	}

	public CustomerNote(Long customerId, Long noteId) {
		this.customerId = customerId;
		this.noteId = noteId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customerNoteId", unique = true, nullable = false)
	public Long getCustomerNoteId() {
		return this.customerNoteId;
	}

	public void setCustomerNoteId(Long customerNoteId) {
		this.customerNoteId = customerNoteId;
	}

	@Column(name = "customerId")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "noteId")
	public Long getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Long noteId) {
		this.noteId = noteId;
	}

}
