package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "weasleydb")
@XmlRootElement
public class Customer implements java.io.Serializable {

	private Long customerId;
	private String firstName;
	private String lastName;
	private String phoneNumber;
	private Long homeAddress;
	private Long workAddress;

	public Customer() {
	}

	public Customer(String firstName, String lastName, String phoneNumber,
			Long homeAddress, Long workAddress) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.homeAddress = homeAddress;
		this.workAddress = workAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customerId", unique = true, nullable = false)
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phoneNumber", length = 25)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "homeAddress")
	public Long getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(Long homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "workAddress")
	public Long getWorkAddress() {
		return this.workAddress;
	}

	public void setWorkAddress(Long workAddress) {
		this.workAddress = workAddress;
	}

}
