package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DeliveryType generated by hbm2java
 */
@Entity
@Table(name = "DeliveryType", catalog = "weasleydb")
@XmlRootElement
public class DeliveryType implements java.io.Serializable {

	private Long deliveryTypeId;
	private String deliveryType;
	private String deliveryTypeText;
	private String description;
	private Character enabled;
	private Character trackable;

	public DeliveryType() {
	}

	public DeliveryType(String deliveryType, String deliveryTypeText,
			String description, Character enabled, Character trackable) {
		this.deliveryType = deliveryType;
		this.deliveryTypeText = deliveryTypeText;
		this.description = description;
		this.enabled = enabled;
		this.trackable = trackable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "deliveryTypeId", unique = true, nullable = false)
	public Long getDeliveryTypeId() {
		return this.deliveryTypeId;
	}

	public void setDeliveryTypeId(Long deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	@Column(name = "deliveryType", length = 5)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "deliveryTypeText", length = 50)
	public String getDeliveryTypeText() {
		return this.deliveryTypeText;
	}

	public void setDeliveryTypeText(String deliveryTypeText) {
		this.deliveryTypeText = deliveryTypeText;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "enabled", length = 1)
	public Character getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Character enabled) {
		this.enabled = enabled;
	}

	@Column(name = "trackable", length = 1)
	public Character getTrackable() {
		return this.trackable;
	}

	public void setTrackable(Character trackable) {
		this.trackable = trackable;
	}

}
