package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * EmailAddress generated by hbm2java
 */
@Entity
@Table(name = "EmailAddress", catalog = "weasleydb")
@XmlRootElement
public class EmailAddress implements java.io.Serializable {

	private Long emailAddressId;
	private String type;
	private String address;
	private Character primaryEmail;
	private Long owner;

	public EmailAddress() {
	}

	public EmailAddress(String type, String address, Character primaryEmail,
			Long owner) {
		this.type = type;
		this.address = address;
		this.primaryEmail = primaryEmail;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "emailAddressId", unique = true, nullable = false)
	public Long getEmailAddressId() {
		return this.emailAddressId;
	}

	public void setEmailAddressId(Long emailAddressId) {
		this.emailAddressId = emailAddressId;
	}

	@Column(name = "type", length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "primaryEmail", length = 1)
	public Character getPrimaryEmail() {
		return this.primaryEmail;
	}

	public void setPrimaryEmail(Character primaryEmail) {
		this.primaryEmail = primaryEmail;
	}

	@Column(name = "owner")
	public Long getOwner() {
		return this.owner;
	}

	public void setOwner(Long owner) {
		this.owner = owner;
	}

}
