package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * FacebookAssociations generated by hbm2java
 */
@Entity
@Table(name = "FacebookAssociations", catalog = "weasleydb")
@XmlRootElement
public class FacebookAssociations implements java.io.Serializable {

	private Long associationId;
	private Long facebookAccountId1;
	private Long facebookAccountId2;

	public FacebookAssociations() {
	}

	public FacebookAssociations(Long facebookAccountId1, Long facebookAccountId2) {
		this.facebookAccountId1 = facebookAccountId1;
		this.facebookAccountId2 = facebookAccountId2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "associationId", unique = true, nullable = false)
	public Long getAssociationId() {
		return this.associationId;
	}

	public void setAssociationId(Long associationId) {
		this.associationId = associationId;
	}

	@Column(name = "facebookAccountId1")
	public Long getFacebookAccountId1() {
		return this.facebookAccountId1;
	}

	public void setFacebookAccountId1(Long facebookAccountId1) {
		this.facebookAccountId1 = facebookAccountId1;
	}

	@Column(name = "facebookAccountId2")
	public Long getFacebookAccountId2() {
		return this.facebookAccountId2;
	}

	public void setFacebookAccountId2(Long facebookAccountId2) {
		this.facebookAccountId2 = facebookAccountId2;
	}

}
