package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * HitCount generated by hbm2java
 */
@Entity
@Table(name = "HitCount", catalog = "weasleydb")
@XmlRootElement
public class HitCount implements java.io.Serializable {

	private Long hitCountId;
	private String server;
	private String webPage;
	private Long currentCount;

	public HitCount() {
	}

	public HitCount(String server, String webPage, Long currentCount) {
		this.server = server;
		this.webPage = webPage;
		this.currentCount = currentCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hitCountId", unique = true, nullable = false)
	public Long getHitCountId() {
		return this.hitCountId;
	}

	public void setHitCountId(Long hitCountId) {
		this.hitCountId = hitCountId;
	}

	@Column(name = "server")
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "webPage")
	public String getWebPage() {
		return this.webPage;
	}

	public void setWebPage(String webPage) {
		this.webPage = webPage;
	}

	@Column(name = "currentCount")
	public Long getCurrentCount() {
		return this.currentCount;
	}

	public void setCurrentCount(Long currentCount) {
		this.currentCount = currentCount;
	}

}
