package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LinkedInAssociations generated by hbm2java
 */
@Entity
@Table(name = "LinkedInAssociations", catalog = "weasleydb")
@XmlRootElement
public class LinkedInAssociations implements java.io.Serializable {

	private Long associationId;
	private Long linkedInAccountId1;
	private Long linkedInAccountId2;

	public LinkedInAssociations() {
	}

	public LinkedInAssociations(Long linkedInAccountId1, Long linkedInAccountId2) {
		this.linkedInAccountId1 = linkedInAccountId1;
		this.linkedInAccountId2 = linkedInAccountId2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "associationId", unique = true, nullable = false)
	public Long getAssociationId() {
		return this.associationId;
	}

	public void setAssociationId(Long associationId) {
		this.associationId = associationId;
	}

	@Column(name = "linkedInAccountId1")
	public Long getLinkedInAccountId1() {
		return this.linkedInAccountId1;
	}

	public void setLinkedInAccountId1(Long linkedInAccountId1) {
		this.linkedInAccountId1 = linkedInAccountId1;
	}

	@Column(name = "linkedInAccountId2")
	public Long getLinkedInAccountId2() {
		return this.linkedInAccountId2;
	}

	public void setLinkedInAccountId2(Long linkedInAccountId2) {
		this.linkedInAccountId2 = linkedInAccountId2;
	}

}
