package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderNote generated by hbm2java
 */
@Entity
@Table(name = "OrderNote", catalog = "weasleydb")
@XmlRootElement
public class OrderNote implements java.io.Serializable {

	private Long orderNoteId;
	private Long orderId;
	private Long noteId;

	public OrderNote() {
	}

	public OrderNote(Long orderId, Long noteId) {
		this.orderId = orderId;
		this.noteId = noteId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderNoteId", unique = true, nullable = false)
	public Long getOrderNoteId() {
		return this.orderNoteId;
	}

	public void setOrderNoteId(Long orderNoteId) {
		this.orderNoteId = orderNoteId;
	}

	@Column(name = "orderId")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "noteId")
	public Long getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Long noteId) {
		this.noteId = noteId;
	}

}
