package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderPayment generated by hbm2java
 */
@Entity
@Table(name = "OrderPayment", catalog = "weasleydb")
@XmlRootElement
public class OrderPayment implements java.io.Serializable {

	private Long orderPaymentId;
	private Long orderId;
	private Long paymentId;
	private BigDecimal amountForOrder;

	public OrderPayment() {
	}

	public OrderPayment(Long orderId, Long paymentId, BigDecimal amountForOrder) {
		this.orderId = orderId;
		this.paymentId = paymentId;
		this.amountForOrder = amountForOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderPaymentId", unique = true, nullable = false)
	public Long getOrderPaymentId() {
		return this.orderPaymentId;
	}

	public void setOrderPaymentId(Long orderPaymentId) {
		this.orderPaymentId = orderPaymentId;
	}

	@Column(name = "orderId")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "paymentId")
	public Long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "amountForOrder", precision = 8)
	public BigDecimal getAmountForOrder() {
		return this.amountForOrder;
	}

	public void setAmountForOrder(BigDecimal amountForOrder) {
		this.amountForOrder = amountForOrder;
	}

}
