package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PaymentNote generated by hbm2java
 */
@Entity
@Table(name = "PaymentNote", catalog = "weasleydb")
@XmlRootElement
public class PaymentNote implements java.io.Serializable {

	private Long paymentNoteId;
	private Long paymentId;
	private Long noteId;

	public PaymentNote() {
	}

	public PaymentNote(Long paymentId, Long noteId) {
		this.paymentId = paymentId;
		this.noteId = noteId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paymentNoteId", unique = true, nullable = false)
	public Long getPaymentNoteId() {
		return this.paymentNoteId;
	}

	public void setPaymentNoteId(Long paymentNoteId) {
		this.paymentNoteId = paymentNoteId;
	}

	@Column(name = "paymentId")
	public Long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "noteId")
	public Long getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Long noteId) {
		this.noteId = noteId;
	}

}
