package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PaypalPayment generated by hbm2java
 */
@Entity
@Table(name = "PaypalPayment", catalog = "weasleydb")
@XmlRootElement
public class PaypalPayment implements java.io.Serializable {

	private Long paypalPaymentId;

	public PaypalPayment() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paypalPaymentId", unique = true, nullable = false)
	public Long getPaypalPaymentId() {
		return this.paypalPaymentId;
	}

	public void setPaypalPaymentId(Long paypalPaymentId) {
		this.paypalPaymentId = paypalPaymentId;
	}

}
