package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PaypalAccount generated by hbm2java
 */
@Entity
@Table(name = "PaypalAccount", catalog = "weasleydb")
@XmlRootElement
public class PaypalAccount implements java.io.Serializable {

	private Long paypalAccountId;

	public PaypalAccount() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paypalAccountId", unique = true, nullable = false)
	public Long getPaypalAccountId() {
		return this.paypalAccountId;
	}

	public void setPaypalAccountId(Long paypalAccountId) {
		this.paypalAccountId = paypalAccountId;
	}

}
