package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", catalog = "weasleydb")
@XmlRootElement
public class Product implements java.io.Serializable {

	private Long productId;
	private String name;
	private String description;
	private Float unitPrice;
	private Float quantityOnHand;

	public Product() {
	}

	public Product(String name, String description, Float unitPrice,
			Float quantityOnHand) {
		this.name = name;
		this.description = description;
		this.unitPrice = unitPrice;
		this.quantityOnHand = quantityOnHand;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "productId", unique = true, nullable = false)
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "name", length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "unitPrice", precision = 12, scale = 0)
	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "quantityOnHand", precision = 12, scale = 0)
	public Float getQuantityOnHand() {
		return this.quantityOnHand;
	}

	public void setQuantityOnHand(Float quantityOnHand) {
		this.quantityOnHand = quantityOnHand;
	}

}
