package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductNote generated by hbm2java
 */
@Entity
@Table(name = "ProductNote", catalog = "weasleydb")
@XmlRootElement
public class ProductNote implements java.io.Serializable {

	private Long productNoteId;
	private Long productId;
	private Long noteId;

	public ProductNote() {
	}

	public ProductNote(Long productId, Long noteId) {
		this.productId = productId;
		this.noteId = noteId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "productNoteId", unique = true, nullable = false)
	public Long getProductNoteId() {
		return this.productNoteId;
	}

	public void setProductNoteId(Long productNoteId) {
		this.productNoteId = productNoteId;
	}

	@Column(name = "productId")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "noteId")
	public Long getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Long noteId) {
		this.noteId = noteId;
	}

}
