package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name = "ShoppingCart", catalog = "weasleydb")
@XmlRootElement
public class ShoppingCart implements java.io.Serializable {

	private Long shoppingCartId;
	private String cartName;
	private Short userCartNumber;
	private String userName;
	private Long customerId;
	private String jsessionId;
	private Date dateCreated;
	private Date expires;
	private Long orderId;

	public ShoppingCart() {
	}

	public ShoppingCart(String cartName, Short userCartNumber, String userName,
			Long customerId, String jsessionId, Date dateCreated, Date expires,
			Long orderId) {
		this.cartName = cartName;
		this.userCartNumber = userCartNumber;
		this.userName = userName;
		this.customerId = customerId;
		this.jsessionId = jsessionId;
		this.dateCreated = dateCreated;
		this.expires = expires;
		this.orderId = orderId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "shoppingCartId", unique = true, nullable = false)
	public Long getShoppingCartId() {
		return this.shoppingCartId;
	}

	public void setShoppingCartId(Long shoppingCartId) {
		this.shoppingCartId = shoppingCartId;
	}

	@Column(name = "cartName", length = 50)
	public String getCartName() {
		return this.cartName;
	}

	public void setCartName(String cartName) {
		this.cartName = cartName;
	}

	@Column(name = "userCartNumber")
	public Short getUserCartNumber() {
		return this.userCartNumber;
	}

	public void setUserCartNumber(Short userCartNumber) {
		this.userCartNumber = userCartNumber;
	}

	@Column(name = "userName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "customerId")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "jsessionId")
	public String getJsessionId() {
		return this.jsessionId;
	}

	public void setJsessionId(String jsessionId) {
		this.jsessionId = jsessionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expires", length = 10)
	public Date getExpires() {
		return this.expires;
	}

	public void setExpires(Date expires) {
		this.expires = expires;
	}

	@Column(name = "orderId")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

}
