package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TwitterAccount generated by hbm2java
 */
@Entity
@Table(name = "TwitterAccount", catalog = "weasleydb")
@XmlRootElement
public class TwitterAccount implements java.io.Serializable {

	private Long twitterAccountId;

	public TwitterAccount() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "twitterAccountId", unique = true, nullable = false)
	public Long getTwitterAccountId() {
		return this.twitterAccountId;
	}

	public void setTwitterAccountId(Long twitterAccountId) {
		this.twitterAccountId = twitterAccountId;
	}

}
