package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TwitterAssociations generated by hbm2java
 */
@Entity
@Table(name = "TwitterAssociations", catalog = "weasleydb")
@XmlRootElement
public class TwitterAssociations implements java.io.Serializable {

	private Long associationId;
	private Long twitterAccountId1;
	private Long twitterAccountId2;

	public TwitterAssociations() {
	}

	public TwitterAssociations(Long twitterAccountId1, Long twitterAccountId2) {
		this.twitterAccountId1 = twitterAccountId1;
		this.twitterAccountId2 = twitterAccountId2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "associationId", unique = true, nullable = false)
	public Long getAssociationId() {
		return this.associationId;
	}

	public void setAssociationId(Long associationId) {
		this.associationId = associationId;
	}

	@Column(name = "twitterAccountId1")
	public Long getTwitterAccountId1() {
		return this.twitterAccountId1;
	}

	public void setTwitterAccountId1(Long twitterAccountId1) {
		this.twitterAccountId1 = twitterAccountId1;
	}

	@Column(name = "twitterAccountId2")
	public Long getTwitterAccountId2() {
		return this.twitterAccountId2;
	}

	public void setTwitterAccountId2(Long twitterAccountId2) {
		this.twitterAccountId2 = twitterAccountId2;
	}

}
