package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * UserId generated by hbm2java
 */
@Entity
@Table(name = "UserId", catalog = "weasleydb", uniqueConstraints = {
		@UniqueConstraint(columnNames = "emailAddress"),
		@UniqueConstraint(columnNames = "userName")})
@XmlRootElement
public class UserId implements java.io.Serializable {

	private Long userId;
	private String userName;
	private String emailAddress;
	private String password;

	public UserId() {
	}

	public UserId(String userName, String emailAddress, String password) {
		this.userName = userName;
		this.emailAddress = emailAddress;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userId", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "userName", unique = true, nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "emailAddress", unique = true, nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
