package com.weasley.store.model;
// Generated Jun 24, 2017 10:00:21 AM by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ZipCode generated by hbm2java
 */
@Entity
@Table(name = "ZipCode", catalog = "weasleydb")
@XmlRootElement
public class ZipCode implements java.io.Serializable {

	private Long zipCodeId;
	private String zip;
	private String city;
	private String state;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private Integer timeZone;
	private Character observesDst;

	public ZipCode() {
	}

	public ZipCode(String zip) {
		this.zip = zip;
	}
	public ZipCode(String zip, String city, String state, BigDecimal latitude,
			BigDecimal longitude, Integer timeZone, Character observesDst) {
		this.zip = zip;
		this.city = city;
		this.state = state;
		this.latitude = latitude;
		this.longitude = longitude;
		this.timeZone = timeZone;
		this.observesDst = observesDst;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "zipCodeId", unique = true, nullable = false)
	public Long getZipCodeId() {
		return this.zipCodeId;
	}

	public void setZipCodeId(Long zipCodeId) {
		this.zipCodeId = zipCodeId;
	}

	@Column(name = "zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "city", length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "latitude", precision = 11, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 11, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "timeZone")
	public Integer getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(Integer timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "observesDST", length = 1)
	public Character getObservesDst() {
		return this.observesDst;
	}

	public void setObservesDst(Character observesDst) {
		this.observesDst = observesDst;
	}

}
